export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Products } from './Products';
export { default as WhyChooseUs } from './WhyChooseUs';
export { default as Gallery } from './Gallery';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as Preloader } from './Preloader';
